name = "cf-tunnel-demo"
main = "./dist/index.mjs"
# compatibility_date = "2023-09-04"
compatibility_date = "2022-11-11"
account_id = "d405a31a6a95efd248be99e323eaff9c"

# node_compat = true

[env.prod]
workers_dev = false

[build]
# command = "npm install && npm run build && copy ./src/driver/**/*.wasm ./dist"
command = "yarn && yarn run build"