version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sql12648414'
      MYSQL_USER: 'sql12648414'
      MYSQL_PASSWORD: 'dt8iKEcGu3'
      MYSQL_ROOT_PASSWORD: 'dt8iKEcGu3'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  cloudflared:
    image: cloudflare/cloudflared:2021.10.5
    environment:
      - TUNNEL_HOSTNAME=${TUNNEL_HOSTNAME}
    volumes:
      - '~/.cloudflared:/etc/cloudflared'
    command: tunnel --url tcp://mysql:3306 --name dev -f
    depends_on:
      - mysql

volumes:
  my-db:
